services:
  - type: web
    name: razorpay-gateway
    runtime: node
    buildCommand: npm install
    startCommand: npm run build && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 