services:
  - type: web
    name: razorpay-gateway
    runtime: node
    buildCommand: npm install
    startCommand: npm run build && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RAZORPAY_KEY_ID
        value: rzp_test_gYowpjeZKdnDNc
      - key: RAZORPAY_KEY_SECRET
        value: 7FHB8nYjATiC0yaFnLl8AXDi
      - key: RAZORPAY_WEBHOOK_SECRET
        value: your_webhook_secret_here 